// Generated by CoffeeScript 1.7.1
(function() {
  var marked, parse, parseBody, parseMetadata;

  marked = require('marked');

  parseMetadata = function(metaBlob) {
    var metadata;
    metadata = {};
    metaBlob.split('\n').forEach(function(metaItem) {
      var key, value, _ref;
      _ref = metaItem.split(':'), key = _ref[0], value = _ref[1];
      return metadata[key] = value.trim();
    });
    return metadata;
  };

  parseBody = function(bodyBlob) {
    return marked(bodyBlob, {
      smartypants: true
    });
  };

  parse = function(post) {
    var body, bodyBlob, meta, metaBlob, splitAt, _ref;
    splitAt = post.indexOf('\n\n');
    _ref = [post.slice(0, splitAt), post.slice(splitAt + 1)], metaBlob = _ref[0], bodyBlob = _ref[1];
    meta = parseMetadata(metaBlob);
    body = parseBody(bodyBlob);
    return {
      meta: meta,
      body: body
    };
  };

  module.exports = parse;

}).call(this);
