// Generated by CoffeeScript 1.9.3
var marked, parse, parseBody, parseMetadata;

marked = require('marked');

parseMetadata = function(metaBlob) {
  var metadata;
  metadata = {};
  metaBlob.split('\n').forEach(function(metaItem) {
    var key, ref, value;
    ref = metaItem.split(':'), key = ref[0], value = ref[1];
    return metadata[key] = value.trim();
  });
  return metadata;
};

parseBody = function(bodyBlob) {
  return marked(bodyBlob, {
    smartypants: true
  });
};

parse = function(post) {
  var body, bodyBlob, meta, metaBlob, ref, splitAt;
  splitAt = post.indexOf('\n\n');
  ref = [post.slice(0, splitAt), post.slice(splitAt + 1)], metaBlob = ref[0], bodyBlob = ref[1];
  meta = parseMetadata(metaBlob);
  body = parseBody(bodyBlob);
  return {
    meta: meta,
    body: body
  };
};

module.exports = parse;
